export type Lang = "en" | "es" | "pt" | "pl" | "ru";

export function asLang(v: string): Lang {
  return (["en", "es", "pt", "pl", "ru"] as Lang[]).includes(v as Lang) ? (v as Lang) : "en";
}

export const CAL_S = {
  en: {
    title: "Calendar", loading: "Loading…",
    tabs: { services: "Services", bookings: "Bookings", blocked: "Blocked Dates" },
    svc: {
      new: "+ New Service", edit: "Edit Service", create: "Create Service", save: "Save Changes",
      pause: "Pause", reactivate: "Reactivate", delete: "Delete", paused: "PAUSED",
      name: "Service Name", duration: "Duration (minutes)", price: "Price",
      description: "Description", color: "Color", timezone: "Your Timezone",
      link: "Public Booking Link", copy: "Copy", copied: "Link copied!",
      empty: "No services yet. Create your first one.",
      selectHint: "Select a service or create one",
      selectSub: "Each service gets a unique booking page your clients use to schedule with you.",
      saved: "Service saved.",
    },
    avail: {
      title: "Weekly Availability", save: "Save Availability", saved: "Availability saved.",
      weekdays: "Mon–Fri", allDays: "All Days", none: "None", unavailable: "Unavailable", to: "to",
    },
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    bkg: {
      confirm: "✓ Confirm & Email Client", decline: "Decline",
      complete: "Mark Completed", cancel: "Cancel This", cancelSeries: "Cancel Series",
      revenue: "revenue", none: (f: string) => "No " + f + " bookings.",
      setRecurrence: "Set as Recurring", recurrenceTitle: "Make this a recurring appointment",
      occurrences: "occurrences", apply: "Apply Recurrence", applying: "Setting up series…",
      seriesLabel: "Series", cancelFrom: "Cancel from here onward",
      expandSeries: "Show series", collapseSeries: "Hide series",
    },
    blk: {
      hint: "Blocked dates are hidden from all booking pages.",
      title: "Block a Date", date: "Date *", reason: "Reason (optional)",
      btn: "Block Date", remove: "Remove",
      upcoming: (n: number) => "Upcoming Blocked Dates (" + n + ")",
      empty: "No blocked dates.",
    },
    status: { pending: "pending", confirmed: "confirmed", completed: "completed", cancelled: "cancelled" },
    recurrence: { none: "One-time", weekly: "Weekly", biweekly: "Every 2 weeks", monthly: "Monthly", yearly: "Yearly" },
  },
  es: {
    title: "Calendario", loading: "Cargando…",
    tabs: { services: "Servicios", bookings: "Reservas", blocked: "Fechas Bloqueadas" },
    svc: {
      new: "+ Nuevo Servicio", edit: "Editar Servicio", create: "Crear Servicio", save: "Guardar Cambios",
      pause: "Pausar", reactivate: "Reactivar", delete: "Eliminar", paused: "PAUSADO",
      name: "Nombre del Servicio", duration: "Duración (minutos)", price: "Precio",
      description: "Descripción", color: "Color", timezone: "Tu Zona Horaria",
      link: "Enlace de Reserva Público", copy: "Copiar", copied: "¡Enlace copiado!",
      empty: "Aún no hay servicios.", selectHint: "Selecciona un servicio o crea uno",
      selectSub: "Cada servicio obtiene una página de reservas pública.", saved: "Servicio guardado.",
    },
    avail: {
      title: "Disponibilidad Semanal", save: "Guardar Disponibilidad", saved: "Disponibilidad guardada.",
      weekdays: "Lun–Vie", allDays: "Todos", none: "Ninguno", unavailable: "No disponible", to: "a",
    },
    days: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    bkg: {
      confirm: "✓ Confirmar y Enviar Email", decline: "Rechazar",
      complete: "Marcar Completado", cancel: "Cancelar esta", cancelSeries: "Cancelar Serie",
      revenue: "ingresos", none: (f: string) => "No hay reservas " + f + ".",
      setRecurrence: "Hacer recurrente", recurrenceTitle: "Convertir en cita recurrente",
      occurrences: "ocurrencias", apply: "Aplicar Recurrencia", applying: "Configurando serie…",
      seriesLabel: "Serie", cancelFrom: "Cancelar desde aquí",
      expandSeries: "Ver serie", collapseSeries: "Ocultar serie",
    },
    blk: {
      hint: "Las fechas bloqueadas no aparecen en las páginas de reservas.",
      title: "Bloquear una Fecha", date: "Fecha *", reason: "Motivo (opcional)",
      btn: "Bloquear Fecha", remove: "Eliminar",
      upcoming: (n: number) => "Fechas Bloqueadas Próximas (" + n + ")",
      empty: "Sin fechas bloqueadas.",
    },
    status: { pending: "pendiente", confirmed: "confirmado", completed: "completado", cancelled: "cancelado" },
    recurrence: { none: "Una vez", weekly: "Semanal", biweekly: "Cada 2 semanas", monthly: "Mensual", yearly: "Anual" },
  },
  pt: {
    title: "Calendário", loading: "Carregando…",
    tabs: { services: "Serviços", bookings: "Reservas", blocked: "Datas Bloqueadas" },
    svc: {
      new: "+ Novo Serviço", edit: "Editar Serviço", create: "Criar Serviço", save: "Salvar Alterações",
      pause: "Pausar", reactivate: "Reativar", delete: "Excluir", paused: "PAUSADO",
      name: "Nome do Serviço", duration: "Duração (minutos)", price: "Preço",
      description: "Descrição", color: "Cor", timezone: "Seu Fuso Horário",
      link: "Link de Reserva Público", copy: "Copiar", copied: "Link copiado!",
      empty: "Nenhum serviço ainda.", selectHint: "Selecione um serviço ou crie um",
      selectSub: "Cada serviço tem uma página de reservas pública.", saved: "Serviço salvo.",
    },
    avail: {
      title: "Disponibilidade Semanal", save: "Salvar Disponibilidade", saved: "Disponibilidade salva.",
      weekdays: "Seg–Sex", allDays: "Todos", none: "Nenhum", unavailable: "Indisponível", to: "até",
    },
    days: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    bkg: {
      confirm: "✓ Confirmar e Enviar Email", decline: "Recusar",
      complete: "Marcar como Concluído", cancel: "Cancelar esta", cancelSeries: "Cancelar Série",
      revenue: "receita", none: (f: string) => "Nenhuma reserva " + f + ".",
      setRecurrence: "Tornar recorrente", recurrenceTitle: "Converter em consulta recorrente",
      occurrences: "ocorrências", apply: "Aplicar Recorrência", applying: "Configurando série…",
      seriesLabel: "Série", cancelFrom: "Cancelar daqui em diante",
      expandSeries: "Ver série", collapseSeries: "Ocultar série",
    },
    blk: {
      hint: "Datas bloqueadas não aparecem nas páginas de reservas.",
      title: "Bloquear uma Data", date: "Data *", reason: "Motivo (opcional)",
      btn: "Bloquear Data", remove: "Remover",
      upcoming: (n: number) => "Datas Bloqueadas Próximas (" + n + ")",
      empty: "Sem datas bloqueadas.",
    },
    status: { pending: "pendente", confirmed: "confirmado", completed: "concluído", cancelled: "cancelado" },
    recurrence: { none: "Uma vez", weekly: "Semanal", biweekly: "A cada 2 semanas", monthly: "Mensal", yearly: "Anual" },
  },
  pl: {
    title: "Kalendarz", loading: "Ładowanie…",
    tabs: { services: "Usługi", bookings: "Rezerwacje", blocked: "Zablokowane Daty" },
    svc: {
      new: "+ Nowa Usługa", edit: "Edytuj Usługę", create: "Utwórz Usługę", save: "Zapisz Zmiany",
      pause: "Wstrzymaj", reactivate: "Reaktywuj", delete: "Usuń", paused: "WSTRZYMANO",
      name: "Nazwa Usługi", duration: "Czas trwania (minuty)", price: "Cena",
      description: "Opis", color: "Kolor", timezone: "Twoja Strefa Czasowa",
      link: "Publiczny Link Rezerwacji", copy: "Kopiuj", copied: "Link skopiowany!",
      empty: "Brak usług.", selectHint: "Wybierz usługę lub utwórz nową",
      selectSub: "Każda usługa ma publiczną stronę rezerwacji.", saved: "Usługa zapisana.",
    },
    avail: {
      title: "Tygodniowa Dostępność", save: "Zapisz Dostępność", saved: "Dostępność zapisana.",
      weekdays: "Pon–Pt", allDays: "Wszystkie", none: "Żaden", unavailable: "Niedostępny", to: "do",
    },
    days: ["Nd", "Pn", "Wt", "Śr", "Cz", "Pt", "Sb"],
    bkg: {
      confirm: "✓ Potwierdź i wyślij email", decline: "Odrzuć",
      complete: "Oznacz jako ukończone", cancel: "Anuluj tę", cancelSeries: "Anuluj Serię",
      revenue: "przychód", none: (f: string) => "Brak rezerwacji: " + f + ".",
      setRecurrence: "Ustaw jako cykliczne", recurrenceTitle: "Ustaw cykliczne spotkanie",
      occurrences: "wystąpień", apply: "Zastosuj Cykliczność", applying: "Konfigurowanie serii…",
      seriesLabel: "Seria", cancelFrom: "Anuluj od tego momentu",
      expandSeries: "Pokaż serię", collapseSeries: "Ukryj serię",
    },
    blk: {
      hint: "Zablokowane daty nie są widoczne na stronach rezerwacji.",
      title: "Zablokuj Datę", date: "Data *", reason: "Powód (opcjonalnie)",
      btn: "Zablokuj Datę", remove: "Usuń",
      upcoming: (n: number) => "Nadchodzące Zablokowane Daty (" + n + ")",
      empty: "Brak zablokowanych dat.",
    },
    status: { pending: "oczekująca", confirmed: "potwierdzona", completed: "ukończona", cancelled: "anulowana" },
    recurrence: { none: "Jednorazowo", weekly: "Co tydzień", biweekly: "Co 2 tygodnie", monthly: "Co miesiąc", yearly: "Co rok" },
  },
  ru: {
    title: "Календарь", loading: "Загрузка…",
    tabs: { services: "Услуги", bookings: "Бронирования", blocked: "Заблокированные Даты" },
    svc: {
      new: "+ Новая Услуга", edit: "Редактировать Услугу", create: "Создать Услугу", save: "Сохранить Изменения",
      pause: "Приостановить", reactivate: "Возобновить", delete: "Удалить", paused: "ПАУЗА",
      name: "Название Услуги", duration: "Продолжительность (мин)", price: "Цена",
      description: "Описание", color: "Цвет", timezone: "Ваш Часовой Пояс",
      link: "Публичная Ссылка", copy: "Копировать", copied: "Ссылка скопирована!",
      empty: "Нет услуг.", selectHint: "Выберите услугу или создайте новую",
      selectSub: "Каждая услуга получает публичную страницу бронирования.", saved: "Услуга сохранена.",
    },
    avail: {
      title: "Еженедельная Доступность", save: "Сохранить Доступность", saved: "Доступность сохранена.",
      weekdays: "Пн–Пт", allDays: "Все дни", none: "Никакой", unavailable: "Недоступно", to: "до",
    },
    days: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
    bkg: {
      confirm: "✓ Подтвердить и отправить email", decline: "Отклонить",
      complete: "Отметить выполненным", cancel: "Отменить это", cancelSeries: "Отменить Серию",
      revenue: "доход", none: (f: string) => "Нет бронирований: " + f + ".",
      setRecurrence: "Сделать повторяющимся", recurrenceTitle: "Установить повторяющуюся встречу",
      occurrences: "встреч", apply: "Применить Повторение", applying: "Настройка серии…",
      seriesLabel: "Серия", cancelFrom: "Отменить с этого момента",
      expandSeries: "Показать серию", collapseSeries: "Скрыть серию",
    },
    blk: {
      hint: "Заблокированные даты скрыты на страницах бронирования.",
      title: "Заблокировать Дату", date: "Дата *", reason: "Причина (необязательно)",
      btn: "Заблокировать Дату", remove: "Удалить",
      upcoming: (n: number) => "Ближайшие Заблокированные Даты (" + n + ")",
      empty: "Нет заблокированных дат.",
    },
    status: { pending: "ожидает", confirmed: "подтверждено", completed: "завершено", cancelled: "отменено" },
    recurrence: { none: "Однократно", weekly: "Еженедельно", biweekly: "Каждые 2 недели", monthly: "Ежемесячно", yearly: "Ежегодно" },
  },
};
