[
  {"name":"Alamo","category_key":"travel_services","region":"global","network":"Admitad","url":"https://codeaven.com/g/ect9jcqrbyad273170bc46fc09ba31/","tier":1},
  {"name":"Localrent","category_key":"travel_services","region":"global","network":"Travelpayouts","url":"https://localrent.tpo.lv/XS0CqdMP","tier":1},
  {"name":"Economybookings","category_key":"travel_services","region":"global","network":"Travelpayouts","url":"https://economybookings.tpo.lv/jSFMPEPA","tier":2},
  {"name":"QEEQ","category_key":"travel_services","region":"global","network":"Travelpayouts","url":"https://qeeq.tpo.lv/jklB4Pbm","tier":2},
  {"name":"AutoEurope","category_key":"travel_services","region":"global","network":"Travelpayouts","url":"https://autoeurope.tpo.lv/t84AzZbO","tier":3},
  {"name":"Europcar AU/NZ","category_key":"travel_services","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=10777&awinaffid=2834806","tier":3},
  {"name":"GetRentacar","category_key":"travel_services","region":"global","network":"Travelpayouts","url":"https://getrentacar.tpo.lv/OR2TWduQ","tier":3},
  {"name":"Jumbo Car Costa Rica","category_key":"travel_services","region":"latam","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=123066&awinaffid=2834806","tier":3},

  {"name":"Kapitalwise","category_key":"finance","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=113822&awinaffid=2834806","tier":2},
  {"name":"Countabout","category_key":"finance","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=35984&awinaffid=2834806","tier":3},
  {"name":"FileYourTaxes","category_key":"finance","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=71769&awinaffid=2834806","tier":3},
  {"name":"Você RH","category_key":"finance","region":"br","network":"Admitad","url":"https://kjuzv.com/g/wxghlxbcctad273170bca062c62e7a/","tier":3},

  {"name":"CVC BR","category_key":"flights","region":"br","network":"Admitad","url":"https://rkdro.cFtrivago
    om/g/xo8ehfl68mad273170bcafa41ba253/","tier":1},
  {"name":"Kiwi","category_key":"flights","region":"br","network":"Travelpayouts","url":"https://booking.tpo.lv/enwsEbCs","tier":1},
  {"name":"Kiwi","category_key":"flights","region":"ca","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=19859&awinaffid=2834806","tier":1},
  {"name":"Kiwi","category_key":"flights","region":"global","network":"Travelpayouts","url":"https://booking.tpo.lv/enwsEbCs","tier":1},
  {"name":"Kiwi","category_key":"flights","region":"mx","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=20563&awinaffid=2834806","tier":1},
  {"name":"Kiwi","category_key":"flights","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=19856&awinaffid=2834806","tier":1},
  {"name":"Aviasales","category_key":"flights","region":"global","network":"Travelpayouts","url":"https://aviasales.tpo.lv/VoWXgFFm","tier":2},

  {"name":"Trivago","category_key":"hotels","region":"br","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=105937&awinaffid=2834806","tier":1},
  {"name":"Trivago","category_key":"hotels","region":"eu","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=105923&awinaffid=2834806","tier":1},
  {"name":"Trivago","category_key":"hotels","region":"mx","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=105931&awinaffid=2834806","tier":1},
  {"name":"Trivago","category_key":"hotels","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=66034&awinaffid=2834806","tier":1},
  {"name":"H10 Hotels","category_key":"hotels","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=5280&awinaffid=2834806","tier":2},
  {"name":"Sirenis Hotels","category_key":"hotels","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=109948&awinaffid=2834806","tier":2},
  {"name":"Trivago","category_key":"hotels","region":"latam","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=105929&awinaffid=2834806","tier":2},
  {"name":"Zenhotels","category_key":"hotels","region":"global","network":"Admitad","url":"https://qwpeg.com/g/qpi6kwbvr0ad273170bc2f6f9b0ac2/","tier":2},
  {"name":"AURAS Travel Insurance","category_key":"insurance","region":"global","network":"Admitad","url":"https://ogsib.com/g/g86qhgosread273170bc102b8feede/","tier":1},
  {"name":"AirHelp","category_key":"insurance","region":"br","network":"Admitad","url":"https://rzekl.com/g/ap539e660sad273170bcf76382dc8c/","tier":1},
  {"name":"EKTA Insurance","category_key":"insurance","region":"global","network":"Travelpayouts","url":"https://ektatraveling.tpo.lv/XWbZbj8S","tier":1},
  {"name":"AirHelp","category_key":"insurance","region":"global","network":"Travelpayouts","url":"https://airhelp.tpo.lv/EPrGDSO3","tier":2},
  {"name":"Melhor Seguro","category_key":"insurance","region":"br","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=120992&awinaffid=2834806","tier":2},
  {"name":"Compensair","category_key":"insurance","region":"global","network":"Travelpayouts","url":"https://compensair.tpo.lv/wxDDCITG","tier":3},

  {"name":"Amazon","category_key":"marketplace","region":"global","network":"Amazon","url":"https://www.amazon.com/?tag=signalboostai-20","tier":1},
  {"name":"Amazon BR","category_key":"marketplace","region":"br","network":"Amazon","url":"https://www.amazon.com.br/?tag=signalboostai-20","tier":1},
  {"name":"Amazon PL","category_key":"marketplace","region":"pl","network":"Amazon","url":"https://www.amazon.pl/?tag=signalboostai-20","tier":1},
  {"name":"AliExpress PL","category_key":"marketplace","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=12044&awinaffid=2834806","tier":2},
  {"name":"Alibaba","category_key":"marketplace","region":"global","network":"Admitad","url":"https://rzekl.com/g/pm1aev55clad273170bc219aa26f6f/","tier":2},
  {"name":"Amazon MX","category_key":"marketplace","region":"mx","network":"Amazon","url":"https://www.amazon.com.mx/?tag=signalboostai-20","tier":2},
  {"name":"Bella Storia PL","category_key":"marketplace","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=10351&awinaffid=2834806","tier":2},
  {"name":"Converse PL","category_key":"marketplace","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=21652&awinaffid=2834806","tier":2},
  {"name":"TWOJEMEBLE PL","category_key":"marketplace","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=21015&awinaffid=2834806","tier":2},
  {"name":"Weneve PL","category_key":"marketplace","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=19605&awinaffid=2834806","tier":2},
  {"name":"Cybercart PL","category_key":"marketplace","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=122886&awinaffid=2834806","tier":2},

  {"name":"Proton VPN","category_key":"products_tools","region":"global","network":"Admitad","url":"https://ntzgd.com/g/px9exodsjkad273170bc08612d8f27/","tier":1},
  {"name":"Cozeware","category_key":"products_tools","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=123618&awinaffid=2834806","tier":2},
  {"name":"ESET","category_key":"products_tools","region":"br","network":"Admitad","url":"https://rzekl.com/g/ad0wrqec9gad273170bc2ca1814dd2/","tier":2},
  {"name":"UdPower","category_key":"products_tools","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=123956&awinaffid=2834806","tier":2},
  {"name":"Guldi","category_key":"products_tools","region":"br","network":"Admitad","url":"https://bednari.com/g/p1zsxhi8clad273170bc3e86b72106/","tier":3},
  {"name":"PearlMountain Limited","category_key":"products_tools","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=90241&awinaffid=2834806","tier":3},
  {"name":"SuperBox","category_key":"products_tools","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=81755&awinaffid=2834806","tier":3},
  {"name":"TikTok Lite","category_key":"products_tools","region":"br","network":"Admitad","url":"https://sgkaa.com/g/4811p4g2ogad273170bc01ff74d73d/","tier":3},
  {"name":"Valerion","category_key":"products_tools","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=113200&awinaffid=2834806","tier":3},
  {"name":"Bloomcabin Poland","category_key":"products_tools","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=119327&awinaffid=2834806","tier":2},
  {"name":"DAX PL","category_key":"products_tools","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=21762&awinaffid=2834806","tier":2},
  {"name":"Swiat Supli PL","category_key":"products_tools","region":"pl","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=21762&awinaffid=2834806","tier":2},

  {"name":"Airalo","category_key":"sim","region":"br","network":"Travelpayouts","url":"https://airalo.tpo.lv/eXjKLiuw","tier":1},
  {"name":"Airalo","category_key":"sim","region":"global","network":"Travelpayouts","url":"https://airalo.tpo.lv/eXjKLiuw","tier":1},
  {"name":"Airalo","category_key":"sim","region":"pl","network":"Travelpayouts","url":"https://airalo.tpo.lv/eXjKLiuw","tier":1},
  {"name":"SuperSim","category_key":"sim","region":"br","network":"Admitad","url":"https://dhwnh.com/g/y9fhnvt3b0ad273170bcbc47462f0b/","tier":1},
  {"name":"Saily","category_key":"sim","region":"global","network":"Travelpayouts","url":"https://tp.media/r?marker=715310&trs=513827&p=8979&u=https%3A%2F%2Fsaily.com&campaign_id=629","tier":2},
  {"name":"TurboVPN","category_key":"sim","region":"global","network":"Admitad","url":"https://grfpr.com/g/exe221unkpad273170bcddf84d4c0b/","tier":2},
  {"name":"Yesim","category_key":"sim","region":"global","network":"Travelpayouts","url":"https://yesim.tpo.lv/3vIzBQts","tier":2},
  {"name":"Drimsim","category_key":"sim","region":"global","network":"Travelpayouts","url":"https://drimsim.tpo.lv/PGwr6JTr","tier":3},
  {"name":"Cyber Florist","category_key":"marketplace","region":"global","network":"Admitad","url":"https://yjfca.com/g/75nfprdgefad273170bc5a87002712/","tier":4},
  {"name":"King Koil","category_key":"marketplace","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=115216&awinaffid=2834806","tier":4},
  {"name":"Tsarbomba","category_key":"marketplace","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=109230&awinaffid=2834806","tier":4},
  {"name":"Xuchang Aixiu Hair Products","category_key":"marketplace","region":"global","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=50899&awinaffid=2834806","tier":4},
  {"name":"Radical Storage","category_key":"travel_services","region":"global","network":"Travelpayouts","url":"https://radicalstorage.tpo.lv/tna4hnly","tier":2},
  {"name":"Klook","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://klook.tpo.lv/pTp1NljF","tier":1},
  {"name":"GoCity","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://gocity.tpo.lv/Des5Cgov","tier":2},
  {"name":"Klook","category_key":"tours","region":"br","network":"Travelpayouts","url":"https://klook.tpo.lv/pTp1NljF","tier":2},
  {"name":"Tiqets","category_key":"tours","region":"eu","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=8616&awinaffid=2834806","tier":2},
  {"name":"Tiqets","category_key":"tours","region":"gb","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=12430&awinaffid=2834806","tier":2},
  {"name":"Tiqets","category_key":"tours","region":"us","network":"Awin","url":"https://www.awin1.com/cread.php?awinmid=12428&awinaffid=2834806","tier":2},
  {"name":"WeGoTrip","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://wegotrip.tpo.lv/kKIF0gIW","tier":2},
  {"name":"BigBusTours","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://bigbustours.tpo.lv/grT1QWXA","tier":3},
  {"name":"BikesBooking","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://bikesbooking.tpo.lv/B3zIKanS","tier":3},
  {"name":"EatWith","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://eatwith.tpo.lv/BfAnpZNb","tier":3},
  {"name":"Searadar","category_key":"tours","region":"global","network":"Travelpayouts","url":"https://searadar.tpo.lv/TO4A5eBZ","tier":3},
  {"name":"Kiwitaxi","category_key":"transfers","region":"global","network":"Travelpayouts","url":"https://kiwitaxi.tpo.lv/DVaqmgKo","tier":1},
  {"name":"Welcome Pickups","category_key":"transfers","region":"global","network":"Travelpayouts","url":"https://tpo.lv/XAJOoobr","tier":1},
  {"name":"GetTransfer","category_key":"transfers","region":"global","network":"Travelpayouts","url":"https://gettransfer.tpo.lv/Pb4p9ljm","tier":2},
  {"name":"Intui.travel","category_key":"transfers","region":"global","network":"Travelpayouts","url":"https://intui.tpo.lv/Rrx5VuN3","tier":2},
  {"name":"Quero Passagem","category_key":"transfers","region":"br","network":"Admitad","url":"https://bednari.com/g/97wv4t3aixad273170bc47756b85cb/","tier":2},
  {"name":"Busbud","category_key":"transfers","region":"global","network":"Travelpayouts","url":"https://busbud.tpo.lv/h4C6YPFZ","tier":3},
  {"name":"HolidayTaxis","category_key":"transfers","region":"global","network":"Travelpayouts","url":"https://holidaytaxis.tpo.lv/oHwpbrFt","tier":3}
]
